name:  Lint Go code

on: 
    workflow_call:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-go@v4
              with:
                go-version: '1.21'
                cache: false

            - name: Run golangci-lint
              uses: golangci/golangci-lint-action@v3.7.0
              with:
                version: latest
