name:  Lint Go code

on: 
    workflow_call:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Run golangci-lint
              uses: golangci/golangci-lint-action@v3.7.0
              with:
                version: latest
