name: Pull Request

on:
  pull_request:
    branches: 
      - "main"

jobs:
  foo:
    uses: pilou/public-action

  lint:
    uses: ./.github/workflows/go-lint.yml

  test:
    uses: ./.github/workflows/go-test.yml
  
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.0.0        
        with:
          push: false
          build-args: |
            A_SECRET=${{ secrets.A_SECRET }}
