name: Preproduction

on:
  push:
    branches: 
      - "main"

jobs:
  lint:
    uses: ./.github/workflows/go-lint.yml

  test:
    uses: ./.github/workflows/go-test.yml
  
  build:
    needs:
      - lint
      - test
    uses: ./.github/workflows/docker-build-and-push.yml
    permissions:
      packages: write
    secrets: inherit
    with:
      environment: PreProduction
      image-tag: latest

  deploy:
    needs: 
      - build
    runs-on: ubuntu-latest
    environment: PreProduction
    steps:
      - uses: pilou/rancher1-webhook@main
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          key: ${{ secrets.DEPLOY_KEY }}
          projectId: ${{ secrets.DEPLOY_PROJECTID }}
          image: ${{ vars.DEPLOY_IMAGE }}
          tag: ${{ vars.DEPLOY_TAG }}
