name: Preproduction

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/go-lint.yml

  test:
    uses: ./.github/workflows/go-test.yml
  
  build:
    uses: ./.github/workflows/docker-build-and-push.yml
    permissions:
      packages: write
    with:
      environment: PreProduction
