name: Preproduction

on:
  push:
    branches: [ "main" ]

jobs:
  lint:
    uses: ./.github/workflows/go-lint.yml

  test:
    uses: ./.github/workflows/go-test.yml
  
  build:
    needs:
      - lint
      - test
    uses: ./.github/workflows/docker-build-and-push.yml
    permissions:
      packages: write
    secrets: inherit
    with:
      environment: PreProduction
      image-tag: latest
