name: Production

on:
  push:
    tags:
      - v*.*.*

  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/go-lint.yml

  test:
    uses: ./.github/workflows/go-test.yml

  build:
    uses: ./.github/workflows/docker-build-and-push.yml
    permissions:
      packages: write
    secrets: inherit
    with:
      environment: Production
      image-tag: stable
